// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `assignment2.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package assignment2;

public enum Currency implements java.io.Serializable
{
    
    EUR(0),
    
    USD(1),
    
    CHF(2);

    public int
    value()
    {
        return __value;
    }

    public static Currency
    valueOf(int __v)
    {
        switch(__v)
        {
        case 0:
            return EUR;
        case 1:
            return USD;
        case 2:
            return CHF;
        }
        return null;
    }

    private
    Currency(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 2);
    }

    public static void
    __write(IceInternal.BasicStream __os, Currency __v)
    {
        if(__v == null)
        {
            __os.writeEnum(assignment2.Currency.EUR.value(), 2);
        }
        else
        {
            __os.writeEnum(__v.value(), 2);
        }
    }

    public static Currency
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(2);
        return __validate(__v);
    }

    private static Currency
    __validate(int __v)
    {
        final Currency __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
