// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `assignment2.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package assignment2;

public interface CustomerPrx extends Ice.ObjectPrx
{
    public void login();

    public void login(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login();

    public Ice.AsyncResult begin_login(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(Ice.Callback __cb);

    public Ice.AsyncResult begin_login(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(Callback_Customer_login __cb);

    public Ice.AsyncResult begin_login(java.util.Map<String, String> __ctx, Callback_Customer_login __cb);

    public Ice.AsyncResult begin_login(IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_login(IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_login(java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_login(java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public void end_login(Ice.AsyncResult __result);

    public void logout();

    public void logout(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_logout();

    public Ice.AsyncResult begin_logout(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_logout(Ice.Callback __cb);

    public Ice.AsyncResult begin_logout(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_logout(Callback_Customer_logout __cb);

    public Ice.AsyncResult begin_logout(java.util.Map<String, String> __ctx, Callback_Customer_logout __cb);

    public Ice.AsyncResult begin_logout(IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_logout(IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_logout(java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_logout(java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_logout(Ice.AsyncResult __result);

    public String calcInvestmentInterest(int periodInMonths, int amount, Currency currency)
        throws UserNotLoggedException;

    public String calcInvestmentInterest(int periodInMonths, int amount, Currency currency, java.util.Map<String, String> __ctx)
        throws UserNotLoggedException;

    public Ice.AsyncResult begin_calcInvestmentInterest(int periodInMonths, int amount, Currency currency);

    public Ice.AsyncResult begin_calcInvestmentInterest(int periodInMonths, int amount, Currency currency, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_calcInvestmentInterest(int periodInMonths, int amount, Currency currency, Ice.Callback __cb);

    public Ice.AsyncResult begin_calcInvestmentInterest(int periodInMonths, int amount, Currency currency, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_calcInvestmentInterest(int periodInMonths, int amount, Currency currency, Callback_Customer_calcInvestmentInterest __cb);

    public Ice.AsyncResult begin_calcInvestmentInterest(int periodInMonths, int amount, Currency currency, java.util.Map<String, String> __ctx, Callback_Customer_calcInvestmentInterest __cb);

    public Ice.AsyncResult begin_calcInvestmentInterest(int periodInMonths, 
                                                        int amount, 
                                                        Currency currency, 
                                                        IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_calcInvestmentInterest(int periodInMonths, 
                                                        int amount, 
                                                        Currency currency, 
                                                        IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_calcInvestmentInterest(int periodInMonths, 
                                                        int amount, 
                                                        Currency currency, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_calcInvestmentInterest(int periodInMonths, 
                                                        int amount, 
                                                        Currency currency, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb);

    public String end_calcInvestmentInterest(Ice.AsyncResult __result)
        throws UserNotLoggedException;

    public String calcLoadInterest(int periodInMoths, int amount, Currency currency)
        throws UserNotLoggedException;

    public String calcLoadInterest(int periodInMoths, int amount, Currency currency, java.util.Map<String, String> __ctx)
        throws UserNotLoggedException;

    public Ice.AsyncResult begin_calcLoadInterest(int periodInMoths, int amount, Currency currency);

    public Ice.AsyncResult begin_calcLoadInterest(int periodInMoths, int amount, Currency currency, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_calcLoadInterest(int periodInMoths, int amount, Currency currency, Ice.Callback __cb);

    public Ice.AsyncResult begin_calcLoadInterest(int periodInMoths, int amount, Currency currency, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_calcLoadInterest(int periodInMoths, int amount, Currency currency, Callback_Customer_calcLoadInterest __cb);

    public Ice.AsyncResult begin_calcLoadInterest(int periodInMoths, int amount, Currency currency, java.util.Map<String, String> __ctx, Callback_Customer_calcLoadInterest __cb);

    public Ice.AsyncResult begin_calcLoadInterest(int periodInMoths, 
                                                  int amount, 
                                                  Currency currency, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_calcLoadInterest(int periodInMoths, 
                                                  int amount, 
                                                  Currency currency, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_calcLoadInterest(int periodInMoths, 
                                                  int amount, 
                                                  Currency currency, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_calcLoadInterest(int periodInMoths, 
                                                  int amount, 
                                                  Currency currency, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public String end_calcLoadInterest(Ice.AsyncResult __result)
        throws UserNotLoggedException;

    public Loan[] getLoans()
        throws UserNotLoggedException;

    public Loan[] getLoans(java.util.Map<String, String> __ctx)
        throws UserNotLoggedException;

    public Ice.AsyncResult begin_getLoans();

    public Ice.AsyncResult begin_getLoans(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLoans(Ice.Callback __cb);

    public Ice.AsyncResult begin_getLoans(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLoans(Callback_Customer_getLoans __cb);

    public Ice.AsyncResult begin_getLoans(java.util.Map<String, String> __ctx, Callback_Customer_getLoans __cb);

    public Ice.AsyncResult begin_getLoans(IceInternal.Functional_GenericCallback1<Loan[]> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getLoans(IceInternal.Functional_GenericCallback1<Loan[]> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getLoans(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<Loan[]> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getLoans(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<Loan[]> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Loan[] end_getLoans(Ice.AsyncResult __result)
        throws UserNotLoggedException;

    public Investment[] getInvestments()
        throws UserNotLoggedException;

    public Investment[] getInvestments(java.util.Map<String, String> __ctx)
        throws UserNotLoggedException;

    public Ice.AsyncResult begin_getInvestments();

    public Ice.AsyncResult begin_getInvestments(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getInvestments(Ice.Callback __cb);

    public Ice.AsyncResult begin_getInvestments(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getInvestments(Callback_Customer_getInvestments __cb);

    public Ice.AsyncResult begin_getInvestments(java.util.Map<String, String> __ctx, Callback_Customer_getInvestments __cb);

    public Ice.AsyncResult begin_getInvestments(IceInternal.Functional_GenericCallback1<Investment[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getInvestments(IceInternal.Functional_GenericCallback1<Investment[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getInvestments(java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<Investment[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getInvestments(java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<Investment[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Investment[] end_getInvestments(Ice.AsyncResult __result)
        throws UserNotLoggedException;
}
