// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `assignment2.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package assignment2;

public interface Customer extends Ice.Object,
                                  _CustomerOperations, _CustomerOperationsNC
{
    public static final String ice_staticId = "::assignment2::Customer";

    public static final long serialVersionUID = -1210955526167375016L;
}
