// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `assignment1.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package assignment1;

public final class CounterHolder extends Ice.ObjectHolderBase<Counter>
{
    public
    CounterHolder()
    {
    }

    public
    CounterHolder(Counter value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof Counter)
        {
            value = (Counter)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _CounterDisp.ice_staticId();
    }
}
