// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `FinancialNews.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FinancialNews;

public final class CurrencyHolder extends Ice.Holder<Currency>
{
    public
    CurrencyHolder()
    {
    }

    public
    CurrencyHolder(Currency value)
    {
        super(value);
    }
}
