// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `FinancialNews.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FinancialNews;

public interface FinancialNewsServer extends Ice.Object,
                                             _FinancialNewsServerOperations, _FinancialNewsServerOperationsNC
{
    public static final String ice_staticId = "::FinancialNews::FinancialNewsServer";

    public static final long serialVersionUID = -7734643388281555688L;
}
